#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=984766867491
BundleId=com.techulus.trapdown
ClientId=984766867491-l7atpaduvkhehv88e1dq1o5mcfu9dtv1.apps.googleusercontent.com

*/

#define kAppID "984766867491"
#define kBundleID "com.techulus.trapdown"
#define kClientID "984766867491-l7atpaduvkhehv88e1dq1o5mcfu9dtv1.apps.googleusercontent.com"

#endif


